  # Tasks: Configure UVNC  for Ubuntu systems
  #
  # Supported OS:
  #   - Ubuntu 16.04LTSi
  #   - Ubuntu 18.04LTSi
  #   - Debian 10

  - name: "For OS: Ubuntu 16.04LTS, Arch: amd64"
    import_tasks: ubuntu-1604-amd64.yml
    when:
      - ansible_distribution == "Ubuntu"
      - ansible_distribution_version ==  "16.04"
      - ansible_architecture == "x86_64"

  - name: "For OS: Ubuntu 18.04LTS, Arch: amd64"
    import_tasks: ubuntu-1804-amd64.yml
    when:
      - ansible_distribution == "Ubuntu"
      - ansible_distribution_version ==  "18.04"
      - ansible_architecture == "x86_64"

  - name: "For OS: Debian 10, Arch: amd64"
    import_tasks: debian-10-amd64.yml
    when:
      - ansible_distribution == "Debian"
      - ansible_distribution_version ==  "10"
      - ansible_architecture == "x86_64"
